### ISSUE TITLE
How can I call a method on cell selection?

### ISSUE THREAD

**Issue by NareshShetty** [zmzimpl/ngx-cell-selectable#1]
I want to get the details of the selected rows and store it in array. How can I call any method on cell selection

[StackBlitz Demo](https://stackblitz.com/edit/angular-ivy-y8hwqc?file=src%2Fapp%2Fapp.component.html)

I couldn't find any information about events related to the selection

**Comment by zmzimpl** [comment]
> I want to get the details of the selected rows and store it in array. How can I call any method on cell selection
> 
> [StackBlitz Demo](https://stackblitz.com/edit/angular-ivy-y8hwqc?file=src%2Fapp%2Fapp.component.html)
> 
> I couldn't find any information about events related to the selection

All the information you can get is in the `cellSelectionInfo`. If you want to get the row data of all selected cells, you can get it like this: [StackBlitz Demo](https://stackblitz.com/edit/angular-ivy-1e51tn?embed=1&file=src/app/app.component.ts)
```
  getRows() {
    if (this.cellSelectionInfo.startEl && this.cellSelectionInfo.endEl) {
      const startRowIndex = +this.cellSelectionInfo.startEl.id.split('-')[0];
      const endRowIndex = +this.cellSelectionInfo.endEl.id.split('-')[0];
      const selectedRows = this.data.filter((item, index) => {
        return index >= startRowIndex && index <= endRowIndex;
      });
      console.log(selectedRows);
    }
  }
```
I didn't provide any method here. Maybe I should define `cellSelectionInfoChange` and emit the selected information after the selection is over? I can add it as soon as you need.

**Comment by NareshShetty** [comment]
I can see the selectedcell array in `CellSelectionInfo.selected` in the stackblitz. All the details are there inside the single array.

How can I differentiate the rows?
Do I need to manually loop through the selected ID for that?

`cellSelectionInfoChange` will be great if we want to update anything after selection

Thanks for the super fast response :- )

**Comment by zmzimpl** [comment]
> I can see the selectedcell array in `CellSelectionInfo.selected` in the stackblitz. All the details are there inside the single array.
> 
> How can I differentiate the rows?
> Do I need to manually loop through the selected ID for that?
> 
> `cellSelectionInfoChange` will be great if update anything after selection
> 
> Thanks for the super fast response :- )

If I understand correctly, you want to distinguish which row each selected cell belongs to. I will add three properties of row, rowIndex, and column to each selected cell, so that you can get more information such as row in `cellSelectionInfo.selection[index]`, and I will add `cellSelectionInfoChange` .
The new version will be released this weekend~

**Comment by NareshShetty** [comment]
> If I understand correctly, you want to distinguish which row each selected cell belongs to. I will add three properties of row, rowIndex, and column to each selected cell, so that you can get more information such as row in `cellSelectionInfo.selection[index]`, and I will add `cellSelectionInfoChange` .

Yes you are right. I want to distinguish the selected cells based on row.



> The new version will be released this weekend~

Great 👍

**Comment by zmzimpl** [comment]
> > If I understand correctly, you want to distinguish which row each selected cell belongs to. I will add three properties of row, rowIndex, and column to each selected cell, so that you can get more information such as row in `cellSelectionInfo.selection[index]`, and I will add `cellSelectionInfoChange` .
> 
> Yes you are right. I want to distinguish the selected cells based on row.
> 
> > The new version will be released this weekend~
> 
> Great 👍

Hi, I have released a new version, you can install and try~ [Demo](https://stackblitz.com/edit/angular-ivy-yp7hjq)
